[tool.poetry]
name = "adw"
version = "0.1.1"
description = "appdirs wrapper library"
authors = ["Mark Gemmill <gitlab@markgemmill.com>"]
license = "BSD-4-Clause"
repository = "https://gitlab.com/mgemmill-pypi/adw"
keywords = ["adw", "appdirs"]
classifiers = [
    "Topic :: Software Development :: Libraries",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]

[tool.poetry.dependencies]
python = "^3.6"
appdirs = "^1.4.3"

[tool.poetry.dev-dependencies]
pytest = "^5.3.5"
pytest-cov = "^2.8.1"
flake8 = "^3.7.9"
black = "^19.10b0"
xini = "^0.2.2"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"

[tool.dover]
versioned_files = [
    "pyproject.toml",
    "README.md",
    "src/adw/__init__.py"
]

[tool.black]
verbose = true

[tool.flake8]
statistics = true
ignore = ["E501","W503","E241","E731"]
max-line-length = 80
max-complexity = 7
tee = true
exclude = [
    ".git",
    ".tox",
    "__pycache__",
    "docs",
    "build",
    "dist"
]

[tool.pytest]
addopts = "-vv --strict --cov=adw --cov-report=term-missing"

[tool.coverage.run]
source = "adw"
branch = true

[tool.coverage.paths]
source = "adw"

[tool.coverage.report]
show_missing = true
