[tool.poetry]
name = "pyutok"
version = "0.1.4"

description = "Inspired by a tool I can not find anymore on the internet: utok 1.5. I use it to clean up path settings in large shell script configuration setups."

packages = [
    { include = "utok.py" },
]

authors = ["Berthold HÃ¶llmann <berthold@xn--hllmanns-n4a.de>"]
license = "MIT"

repository = "https://gitlab.com/berhoel/python/pyutok.git"
readme = "README.md"

classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: System :: Shells",
    "Topic :: Utilities"
]

[tool.poetry.dependencies]
python = "^2.7 || >3.5"

[tool.poetry.dev-dependencies]
tox = "^3.14.5"
pytest = [
    {version="^5.3.5", python=">3.5"},
    {version="^4.6", python="^2.7"}
]
pathlib2 = [
    {version="^2.3.5", python = "^2.7"}
]

[tool.poetry.scripts]
utok = 'utok:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

