[tool.poetry]
name = "agilicus"
version = "1.6.0"
description = "Agilicus SDK"
license = "MIT"
authors = ["Agilicus Devs <dev@agilicus.com>"]
readme = "README.md"
include = [ "agilicus_README.md" ]

[tool.poetry.dependencies]
python = "^3.7"
certifi = ">=14.05.14"
six = ">1.10"
python_dateutil = ">2.5.3"
urllib3 = ">1.15.1"
PyJWT = ">=1.5.3,<1.6.0"
connexion = ">=2.2.0,<2.3.0"
requests = ">=2.21.0,<2.30.0"
arrow = ">=0.13.1,<0.14.0"
prettytable = ">=0.7.2,<0.8.0"
oauth2client = ">=4.1.3,<4.2.0"
click-shell = ">=2.0,<3.0"


[tool.poetry.dev-dependencies]
pytest = "^4.6"
black = "^19.10b0"
flake8 = "^3.7.9"
markdown = "^3.2.1"
ptvsd = "^4.3.2"

[tool.poetry.scripts]
agilicus-cli = 'agilicus.main:main'

[tool.black]
line-length = 79
target-version = "1.6.0"
include = '\.pyi?$'
exclude = '''
    \.git
  | \.tox
  | \.venv
  | agilicus_api
  | build
  | dist
'''

# ignore = # E203, E266, E501, W503, F403, F401
[tool.flake8]
exclude = 'agilicus/agilicus_api/**'
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

