[tool.poetry]
name = "syntags"
version = "0.1.0"
description = "A beautiful python syntax to generate HTML."
authors = ["SeparateRecords <me@rob.ac>"]
license = "ISC"
include = ["LICENSE"]
readme = "README.md"
repository = "https://github.com/SeparateRecords/Syntags"
keywords = ["html", "dsl", "markup", "syntax", "tags"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: ISC License (ISCL)",
  "Topic :: Text Processing :: Markup :: HTML"
]

[tool.poetry.dependencies]
python = "^3.8"
# ~~ For markdown ~~
markdown2 = {version = "^2.3.8", optional = true}
pygments = {version = "^2.5.2", optional = true}

[tool.poetry.extras]
markdown = ["markdown2", "pygments"]

[tool.poetry.dev-dependencies]
isort = "^4.3"
pytest = "^5"
pylint = "^2.4.4"
black = "^19.10b0"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
line_length = 88

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
